import PDFDocument from 'pdfkit';

export const reportService = {
  async generateHealthReport(user, dashboardData) {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(24).fillColor('#6366f1').text('Aurora Health Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).fillColor('#333').text(`Generated for: ${user.name}`, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(2);

      doc.fontSize(16).fillColor('#6366f1').text('Health Score');
      doc.fontSize(12).fillColor('#333').text(`Overall Score: ${dashboardData.healthScore?.score || 75}/100`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#6366f1').text('Hydration');
      doc.fontSize(12).fillColor('#333')
        .text(`Today: ${dashboardData.hydration?.current || 0}ml / ${dashboardData.hydration?.goal || 2500}ml`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#6366f1').text('Sleep');
      doc.fontSize(12).fillColor('#333')
        .text(`Today: ${dashboardData.sleep?.hours || 0} hours (Goal: ${dashboardData.sleep?.goal || 8}h)`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#6366f1').text('Habits');
      doc.fontSize(12).fillColor('#333')
        .text(`Completion Rate: ${dashboardData.habits?.rate || 0}% (${dashboardData.habits?.completed || 0}/${dashboardData.habits?.total || 0})`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#6366f1').text('Nutrition');
      doc.fontSize(12).fillColor('#333')
        .text(`Calories: ${dashboardData.nutrition?.calories || 0} / ${dashboardData.nutrition?.goal || 2000}`);
      doc.moveDown(2);

      doc.fontSize(10).fillColor('#999').text('Generated by Aurora AI Health Companion', { align: 'center' });

      doc.end();
    });
  },
};
